version: "3"
services:
  flask:
    build:
      context: flask_app
    image: "flask:dev"
    ports:
      - "5010:5000"
    depends_on:
      - mongo
    external_links:
      - api2_flask_1:flask2
    volumes:
      - .:/opt/app
    environment:
      - FLASK_APP=flask_app.app:app
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]  # Always return error
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      api2_default:
      api1:
        aliases:
          - flask
  mongo:
    image: "mongo"
    ports:
      - "27018:27017"
    networks:
      api1:
        aliases:
          - mongo
networks:
  api2_default:
    external: true
  api1:
    driver: bridge